### ISSUE TITLE
AI

### ISSUE THREAD

**Issue by peterheard01** [kristjankorjus/Replicating-DeepMind#23]
wait a minute... are you saying you have copied deep minds functionality and written your own atari game agent?

**Comment by kuz** [comment]
No.
We attempted to copy their functionality using cuda-convnet2 library.
We achieved some results but not nearly as good as theirs.
Now this project is on hold, because DeepMind has published [their source code](https://github.com/kuz/DeepMind-Atari-Deep-Q-Learner).
For atari game agent we (and they) use [ALE](http://www.arcadelearningenvironment.org/).

**Comment by peterheard01** [comment]
thanks well done for trying...
